language: csharp

sudo: false  # use the new container-based Travis infrastructure 

script: 
  - ./build.sh Release

after_script:
  - zip -r Log-build-$TRAVIS_BUILD_NUMBER.zip ~/Prajna/Log
  
addons:
  artifacts:
    debug: true
    paths:
      - Log-build-$TRAVIS_BUILD_NUMBER.zip 
    s3_region: us-west-2
